<?php
$urbanism_slider_sc = urbanism_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $urbanism_slider_sc ) && strpos( $urbanism_slider_sc, '[' ) !== false && strpos( $urbanism_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( urbanism_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$urbanism_anchor_icon = urbanism_get_theme_option( 'front_page_title_anchor_icon' );
		$urbanism_anchor_text = urbanism_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $urbanism_anchor_icon ) || ! empty( $urbanism_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $urbanism_anchor_icon ) ? ' icon="' . esc_attr( $urbanism_anchor_icon ) . '"' : '' )
									. ( ! empty( $urbanism_anchor_text ) ? ' title="' . esc_attr( $urbanism_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $urbanism_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$urbanism_scheme = urbanism_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $urbanism_scheme ) && ! urbanism_is_inherit( $urbanism_scheme ) ) {
			echo ' scheme_' . esc_attr( $urbanism_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( urbanism_get_theme_option( 'front_page_title_paddings' ) );
		if ( urbanism_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$urbanism_css      = '';
		$urbanism_bg_image = urbanism_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $urbanism_bg_image ) ) {
			$urbanism_css .= 'background-image: url(' . esc_url( urbanism_get_attachment_url( $urbanism_bg_image ) ) . ');';
		}
		if ( ! empty( $urbanism_css ) ) {
			echo ' style="' . esc_attr( $urbanism_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$urbanism_anchor_icon = urbanism_get_theme_option( 'front_page_title_anchor_icon' );
		$urbanism_anchor_text = urbanism_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $urbanism_anchor_icon ) || ! empty( $urbanism_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $urbanism_anchor_icon ) ? ' icon="' . esc_attr( $urbanism_anchor_icon ) . '"' : '' )
									. ( ! empty( $urbanism_anchor_text ) ? ' title="' . esc_attr( $urbanism_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( urbanism_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' urbanism-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$urbanism_css      = '';
			$urbanism_bg_mask  = urbanism_get_theme_option( 'front_page_title_bg_mask' );
			$urbanism_bg_color_type = urbanism_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $urbanism_bg_color_type ) {
				$urbanism_bg_color = urbanism_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $urbanism_bg_color_type ) {
				$urbanism_bg_color = urbanism_get_scheme_color( 'bg_color', $urbanism_scheme );
			} else {
				$urbanism_bg_color = '';
			}
			if ( ! empty( $urbanism_bg_color ) && $urbanism_bg_mask > 0 ) {
				$urbanism_css .= 'background-color: ' . esc_attr(
					1 == $urbanism_bg_mask ? $urbanism_bg_color : urbanism_hex2rgba( $urbanism_bg_color, $urbanism_bg_mask )
				) . ';';
			}
			if ( ! empty( $urbanism_css ) ) {
				echo ' style="' . esc_attr( $urbanism_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$urbanism_caption = urbanism_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $urbanism_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $urbanism_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $urbanism_caption, 'urbanism_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$urbanism_description = urbanism_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $urbanism_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $urbanism_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $urbanism_description ), 'urbanism_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( urbanism_get_theme_option( 'front_page_title_button1_link' ) != '' || urbanism_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						urbanism_show_layout( urbanism_customizer_partial_refresh_front_page_title_button1_link() );
						urbanism_show_layout( urbanism_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
